name: Release Build
on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Publish Release
        run: |
          dotnet publish FileCryptographyTool/FileCryptographyTool.csproj \
            -c Release \
            -r win-x64 \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:PublishTrimmed=true \
            -o published

      - name: Zip Artifacts
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r FileCryptographyTool.zip published/*

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            FileCryptographyTool.zip
            published/FileCryptographyTool.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}